### ISSUE TITLE
Feature: Inlining direct svg files

### ISSUE THREAD

**Issue by piotr-cz** [bienzaaron/vite-plugin-inline-source#329]
I'd like to inline svg files that are directly referenced in `index.html`:

```html
<!DOCTYPE html>
<html lang="en" dir="ltr" translate="no">
  <!-- ... -->
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>

    <!-- Symbols  -->
    <svg class="app-svg-symbols" xmlns="http://www.w3.org/2000/svg">
      <image id="icon-symbol" width="100%" height="100%" href="/src/assets/images/icon.svg" inline-source />
    </svg>
  </body>
</html>
```

But it doesn't work, probably because the match pattern: is looking for  `src=` string:

https://github.com/bienzaaron/vite-plugin-inline-source/blob/4598072f67f127f88193744e7871ed00824d3000/src/index.ts#L45-L46

Is having such feature in scope of this plugin?

**Comment by bienzaaron** [comment]
If you use `<svg src="path/to/svg.svg/>` or `<img src="path/to/svg.svg/>` it should work.


Does that meet your needs, or is there some reason you need to reference your svg using `image`?

**Comment by bienzaaron** [comment]
Generally though, I think it makes sense to allow inlining based on other attributes than just `src`. Feel free to send a PR to add an option 👍

**Comment by piotr-cz** [comment]
Thanks, I'll close this PR then.

Using `<svg src= />` or `<image src />` or `<img src= />` should work, but I guess the `id` attribute would be lost.
